# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch


# Create random tensor
x = torch.rand(7,7)
print(x)

tensor([[0.9891, 0.0651, 0.4164, 0.2507, 0.9891, 0.9653, 0.7804],
        [0.1178, 0.5963, 0.6217, 0.3352, 0.8173, 0.9711, 0.5065],
        [0.6303, 0.7207, 0.3485, 0.9395, 0.1525, 0.6537, 0.9201],
        [0.8681, 0.4272, 0.8799, 0.7077, 0.3296, 0.5600, 0.6692],
        [0.0859, 0.4936, 0.8664, 0.8134, 0.9562, 0.8724, 0.5449],
        [0.6310, 0.9721, 0.9420, 0.6064, 0.2556, 0.1521, 0.0623],
        [0.5671, 0.0100, 0.1683, 0.7466, 0.4175, 0.8504, 0.0728]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
var = torch.rand(1,7)
mul= torch.matmul(x,var.T)
print(mul)
mul, mul.shape

tensor([[2.9119],
        [2.3438],
        [2.9832],
        [2.9755],
        [2.8601],
        [1.9813],
        [1.8931]])


(tensor([[2.9119],
         [2.3438],
         [2.9832],
         [2.9755],
         [2.8601],
         [1.9813],
         [1.8931]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed

torch.manual_seed(0)
# Create two random tensors
X = torch.rand(7,7)
Y = torch.rand(1,7)

# Matrix multiply tensors
mul= torch.matmul(X,Y.T)
print(mul)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
# Check for access to GPU

# Create two random tensors on GPU
var1= torch.rand(2,3).to(device)
var2= torch.rand(2,3).to(device)
print(var1)
print(var2)
# Check for access to GPU

# Create two random tensors on GPU


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_A= var1
tensor_B= var2
mul= torch.matmul(tensor_A,tensor_B.T)
print(mul)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:


# Find max
max = torch.max(mul)
# Find min
min = torch.min(mul)
max, min



(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_idx= torch.argmax(mul)
# Find arg min
min_idx= torch.argmin(mul)
print(max_idx)
print(min_idx)



tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor= torch.rand(1,1,1,10)

# Remove single dimensions

tensor_squeeze= torch.squeeze(tensor)
# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeeze, tensor_squeeze.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
